-- MySQL Script generated by MySQL Workbench
-- Thu May  6 19:40:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SistemaHospitalar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SistemaHospitalar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SistemaHospitalar` DEFAULT CHARACTER SET utf8 ;
USE `SistemaHospitalar` ;

-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Sexo` (
  `Codigo_Sexo` INT NOT NULL,
  `Descricao_Sexo` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo_Sexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Medico` (
  `CRM` INT NOT NULL,
  `CPF_Medico` INT NOT NULL,
  `Nome_Medico` VARCHAR(45) NOT NULL,
  `Titulacao_Medico` VARCHAR(45) NOT NULL,
  `Data_Nascimento_Medico` DATETIME NOT NULL,
  `Data_Contratacao_Medico` DATETIME NOT NULL,
  `Formacao_Medico` VARCHAR(45) NOT NULL,
  `Email_Medico` VARCHAR(45) NULL DEFAULT NULL,
  `Filiacao_Medico` VARCHAR(45) NULL DEFAULT NULL,
  `Estado_Civil_Medico` VARCHAR(45) NULL DEFAULT NULL,
  `Sexo_Codigo_Sexo` INT NOT NULL,
  PRIMARY KEY (`CRM`, `CPF_Medico`, `Sexo_Codigo_Sexo`),
  INDEX `fk_Medico_Sexo1_idx` (`Sexo_Codigo_Sexo` ASC) VISIBLE,
  CONSTRAINT `fk_Medico_Sexo1`
    FOREIGN KEY (`Sexo_Codigo_Sexo`)
    REFERENCES `SistemaHospitalar`.`Sexo` (`Codigo_Sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Hospital` (
  `ID_Hospital` INT NOT NULL AUTO_INCREMENT,
  `Nome_Hospital` VARCHAR(45) NOT NULL,
  `Especialidade_Hospital` VARCHAR(45) NOT NULL,
  `Endereco_Hospital` VARCHAR(45) NOT NULL,
  `Telefone_Hospital` INT NOT NULL,
  `Porte_Hospital` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Hospital`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Enfermaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Enfermaria` (
  `Codigo_Enfermaria` INT NOT NULL,
  `Descricao_Enfermaria` VARCHAR(45) NOT NULL,
  `Ala_Enfermaria` VARCHAR(45) NOT NULL,
  `Hospital_Codigo_Hospital` INT NOT NULL,
  PRIMARY KEY (`Codigo_Enfermaria`, `Hospital_Codigo_Hospital`),
  INDEX `fk_Enfermaria_Hospital_idx` (`Hospital_Codigo_Hospital` ASC) VISIBLE,
  CONSTRAINT `fk_Enfermaria_Hospital`
    FOREIGN KEY (`Hospital_Codigo_Hospital`)
    REFERENCES `SistemaHospitalar`.`Hospital` (`ID_Hospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Enfermeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Enfermeiro` (
  `COREN` INT NOT NULL,
  `CPF_Enfermeiro` INT NOT NULL,
  `Nome_Enfermeiro` VARCHAR(45) NOT NULL,
  `Titulacao_Enfermeiro` VARCHAR(45) NOT NULL,
  `Data_Nascimento_Enfermeiro` DATETIME NOT NULL,
  `Data_Contratacao_Enfermeiro` DATETIME NOT NULL,
  `Formacao_Enfermeiro` VARCHAR(45) NOT NULL,
  `Email_Enfermeiro` VARCHAR(45) NULL DEFAULT NULL,
  `Estado_Civil_Enfermeiro` VARCHAR(45) NULL DEFAULT NULL,
  `Filiacao_Enfermeiro` VARCHAR(45) NULL DEFAULT NULL,
  `Enfermaria_Codigo_Enfermaria` INT NOT NULL,
  `Enfermaria_Hospital_Codigo_Hospital` INT NOT NULL,
  `Sexo_Codigo_Sexo` INT NOT NULL,
  PRIMARY KEY (`COREN`, `CPF_Enfermeiro`, `Enfermaria_Codigo_Enfermaria`, `Enfermaria_Hospital_Codigo_Hospital`, `Sexo_Codigo_Sexo`),
  INDEX `fk_Enfermeiro_Enfermaria1_idx` (`Enfermaria_Codigo_Enfermaria` ASC, `Enfermaria_Hospital_Codigo_Hospital` ASC) VISIBLE,
  INDEX `fk_Enfermeiro_Sexo1_idx` (`Sexo_Codigo_Sexo` ASC) VISIBLE,
  CONSTRAINT `fk_Enfermeiro_Enfermaria1`
    FOREIGN KEY (`Enfermaria_Codigo_Enfermaria` , `Enfermaria_Hospital_Codigo_Hospital`)
    REFERENCES `SistemaHospitalar`.`Enfermaria` (`Codigo_Enfermaria` , `Hospital_Codigo_Hospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enfermeiro_Sexo1`
    FOREIGN KEY (`Sexo_Codigo_Sexo`)
    REFERENCES `SistemaHospitalar`.`Sexo` (`Codigo_Sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Paciente` (
  `Codigo_Paciente` INT NOT NULL,
  `CPF_Paciente` INT NOT NULL,
  `Nome_Paciente` VARCHAR(45) NOT NULL,
  `Data_Nascimento_Paciente` DATETIME NOT NULL,
  `Data_Entrada_Paciente` DATETIME NOT NULL,
  `Convenio_Paciente` VARCHAR(45) NULL DEFAULT NULL,
  `Email_Paciente` VARCHAR(45) NULL DEFAULT NULL,
  `Filiacao_Paciente` VARCHAR(45) NULL DEFAULT NULL,
  `Enfermaria_Codigo_Enfermaria` INT NOT NULL,
  `Enfermaria_Hospital_Codigo_Hospital` INT NOT NULL,
  `Sexo_Codigo_Sexo` INT NOT NULL,
  PRIMARY KEY (`Codigo_Paciente`, `CPF_Paciente`, `Enfermaria_Codigo_Enfermaria`, `Enfermaria_Hospital_Codigo_Hospital`, `Sexo_Codigo_Sexo`),
  INDEX `fk_Paciente_Enfermaria1_idx` (`Enfermaria_Codigo_Enfermaria` ASC, `Enfermaria_Hospital_Codigo_Hospital` ASC) VISIBLE,
  INDEX `fk_Paciente_Sexo1_idx` (`Sexo_Codigo_Sexo` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_Enfermaria1`
    FOREIGN KEY (`Enfermaria_Codigo_Enfermaria` , `Enfermaria_Hospital_Codigo_Hospital`)
    REFERENCES `SistemaHospitalar`.`Enfermaria` (`Codigo_Enfermaria` , `Hospital_Codigo_Hospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_Sexo1`
    FOREIGN KEY (`Sexo_Codigo_Sexo`)
    REFERENCES `SistemaHospitalar`.`Sexo` (`Codigo_Sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Pais` (
  `ID_Pais` INT NOT NULL,
  `Nome_Pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`UF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`UF` (
  `ID_UF` INT NOT NULL,
  `Nome_UF` VARCHAR(45) NOT NULL,
  `Pais_ID_Pais` INT NOT NULL,
  PRIMARY KEY (`ID_UF`, `Pais_ID_Pais`),
  INDEX `fk_UF_Pais1_idx` (`Pais_ID_Pais` ASC) VISIBLE,
  CONSTRAINT `fk_UF_Pais1`
    FOREIGN KEY (`Pais_ID_Pais`)
    REFERENCES `SistemaHospitalar`.`Pais` (`ID_Pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Cidade` (
  `Codigo_Cidade` INT NOT NULL,
  `Nome_Cidade` VARCHAR(45) NOT NULL,
  `UF_ID_UF` INT NOT NULL,
  `UF_Pais_ID_Pais` INT NOT NULL,
  PRIMARY KEY (`Codigo_Cidade`, `UF_ID_UF`, `UF_Pais_ID_Pais`),
  INDEX `fk_Cidade_UF1_idx` (`UF_ID_UF` ASC, `UF_Pais_ID_Pais` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_UF1`
    FOREIGN KEY (`UF_ID_UF` , `UF_Pais_ID_Pais`)
    REFERENCES `SistemaHospitalar`.`UF` (`ID_UF` , `Pais_ID_Pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Bairro` (
  `Codigo_Bairro` INT NOT NULL,
  `Nome_Bairro` VARCHAR(45) NOT NULL,
  `Cidade_Codigo_Cidade` INT NOT NULL,
  `Cidade_UF_ID_UF` INT NOT NULL,
  `Cidade_UF_Pais_ID_Pais` INT NOT NULL,
  PRIMARY KEY (`Codigo_Bairro`, `Cidade_Codigo_Cidade`, `Cidade_UF_ID_UF`, `Cidade_UF_Pais_ID_Pais`),
  INDEX `fk_Bairro_Cidade1_idx` (`Cidade_Codigo_Cidade` ASC, `Cidade_UF_ID_UF` ASC, `Cidade_UF_Pais_ID_Pais` ASC) VISIBLE,
  CONSTRAINT `fk_Bairro_Cidade1`
    FOREIGN KEY (`Cidade_Codigo_Cidade` , `Cidade_UF_ID_UF` , `Cidade_UF_Pais_ID_Pais`)
    REFERENCES `SistemaHospitalar`.`Cidade` (`Codigo_Cidade` , `UF_ID_UF` , `UF_Pais_ID_Pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Tipo_Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Tipo_Endereco` (
  `Codigo_TipoEnde` INT NOT NULL,
  `Descricao_Endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo_TipoEnde`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Endereco` (
  `Codigo_Endereco` INT NOT NULL,
  `CEP_Endereco` INT NOT NULL,
  `Nome_Rua_Endereco` VARCHAR(45) NULL DEFAULT NULL,
  `Complemento_Endereco` VARCHAR(45) NULL DEFAULT NULL,
  `Numero_Endereco` INT NULL DEFAULT NULL,
  `Bairro_Codigo_Bairro` INT NOT NULL,
  `Bairro_Cidade_Codigo_Cidade` INT NOT NULL,
  `Bairro_Cidade_UF_ID_UF` INT NOT NULL,
  `Bairro_Cidade_UF_Pais_ID_Pais` INT NOT NULL,
  `Tipo_Endereco_Codigo_TipoEnde` INT NOT NULL,
  PRIMARY KEY (`Codigo_Endereco`, `Bairro_Codigo_Bairro`, `Bairro_Cidade_Codigo_Cidade`, `Bairro_Cidade_UF_ID_UF`, `Bairro_Cidade_UF_Pais_ID_Pais`, `Tipo_Endereco_Codigo_TipoEnde`),
  INDEX `fk_Endereco_Bairro1_idx` (`Bairro_Codigo_Bairro` ASC, `Bairro_Cidade_Codigo_Cidade` ASC, `Bairro_Cidade_UF_ID_UF` ASC, `Bairro_Cidade_UF_Pais_ID_Pais` ASC) VISIBLE,
  INDEX `fk_Endereco_Tipo_Endereco1_idx` (`Tipo_Endereco_Codigo_TipoEnde` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Bairro1`
    FOREIGN KEY (`Bairro_Codigo_Bairro` , `Bairro_Cidade_Codigo_Cidade` , `Bairro_Cidade_UF_ID_UF` , `Bairro_Cidade_UF_Pais_ID_Pais`)
    REFERENCES `SistemaHospitalar`.`Bairro` (`Codigo_Bairro` , `Cidade_Codigo_Cidade` , `Cidade_UF_ID_UF` , `Cidade_UF_Pais_ID_Pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Tipo_Endereco1`
    FOREIGN KEY (`Tipo_Endereco_Codigo_TipoEnde`)
    REFERENCES `SistemaHospitalar`.`Tipo_Endereco` (`Codigo_TipoEnde`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Laboratorio` (
  `Codigo_Laboratorio` INT NOT NULL,
  `Descricao_Laboratorio` VARCHAR(45) NOT NULL,
  `Telefone_Laboratorio` VARCHAR(45) NOT NULL,
  `Endereco_Codigo_Endereco` INT NOT NULL,
  `Endereco_Bairro_Codigo_Bairro` INT NOT NULL,
  `Endereco_Bairro_Cidade_Codigo_Cidade` INT NOT NULL,
  `Endereco_Bairro_Cidade_UF_ID_UF` INT NOT NULL,
  `Endereco_Bairro_Cidade_UF_Pais_ID_Pais` INT NOT NULL,
  `Endereco_Tipo_Endereco_Codigo_TipoEnde` INT NOT NULL,
  PRIMARY KEY (`Codigo_Laboratorio`, `Endereco_Codigo_Endereco`, `Endereco_Bairro_Codigo_Bairro`, `Endereco_Bairro_Cidade_Codigo_Cidade`, `Endereco_Bairro_Cidade_UF_ID_UF`, `Endereco_Bairro_Cidade_UF_Pais_ID_Pais`, `Endereco_Tipo_Endereco_Codigo_TipoEnde`),
  INDEX `fk_Laboratorio_Endereco1_idx` (`Endereco_Codigo_Endereco` ASC, `Endereco_Bairro_Codigo_Bairro` ASC, `Endereco_Bairro_Cidade_Codigo_Cidade` ASC, `Endereco_Bairro_Cidade_UF_ID_UF` ASC, `Endereco_Bairro_Cidade_UF_Pais_ID_Pais` ASC, `Endereco_Tipo_Endereco_Codigo_TipoEnde` ASC) VISIBLE,
  CONSTRAINT `fk_Laboratorio_Endereco1`
    FOREIGN KEY (`Endereco_Codigo_Endereco` , `Endereco_Bairro_Codigo_Bairro` , `Endereco_Bairro_Cidade_Codigo_Cidade` , `Endereco_Bairro_Cidade_UF_ID_UF` , `Endereco_Bairro_Cidade_UF_Pais_ID_Pais` , `Endereco_Tipo_Endereco_Codigo_TipoEnde`)
    REFERENCES `SistemaHospitalar`.`Endereco` (`Codigo_Endereco` , `Bairro_Codigo_Bairro` , `Bairro_Cidade_Codigo_Cidade` , `Bairro_Cidade_UF_ID_UF` , `Bairro_Cidade_UF_Pais_ID_Pais` , `Tipo_Endereco_Codigo_TipoEnde`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Equipamento` (
  `Codigo_Equipamento` INT NOT NULL,
  `Descricao_Equipamento` VARCHAR(45) NOT NULL,
  `Fabricante_Equipamento` VARCHAR(45) NULL DEFAULT NULL,
  `Enfermaria_Codigo_Enfermaria` INT NOT NULL,
  `Enfermaria_Hospital_Codigo_Hospital` INT NOT NULL,
  PRIMARY KEY (`Codigo_Equipamento`, `Enfermaria_Codigo_Enfermaria`, `Enfermaria_Hospital_Codigo_Hospital`),
  INDEX `fk_Equipamento_Enfermaria1_idx` (`Enfermaria_Codigo_Enfermaria` ASC, `Enfermaria_Hospital_Codigo_Hospital` ASC) VISIBLE,
  CONSTRAINT `fk_Equipamento_Enfermaria1`
    FOREIGN KEY (`Enfermaria_Codigo_Enfermaria` , `Enfermaria_Hospital_Codigo_Hospital`)
    REFERENCES `SistemaHospitalar`.`Enfermaria` (`Codigo_Enfermaria` , `Hospital_Codigo_Hospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Atende`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Atende` (
  `Paciente_Codigo_Paciente` INT NOT NULL,
  `Paciente_CPF_Paciente` INT NOT NULL,
  `Paciente_Enfermaria_Codigo_Enfermaria` INT NOT NULL,
  `Paciente_Enfermaria_Hospital_Codigo_Hospital` INT NOT NULL,
  `Medico_CRM` INT NOT NULL,
  `Medico_CPF_Medico` INT NOT NULL,
  PRIMARY KEY (`Paciente_Codigo_Paciente`, `Paciente_CPF_Paciente`, `Paciente_Enfermaria_Codigo_Enfermaria`, `Paciente_Enfermaria_Hospital_Codigo_Hospital`, `Medico_CRM`, `Medico_CPF_Medico`),
  INDEX `fk_Paciente_has_Medico_Medico1_idx` (`Medico_CRM` ASC, `Medico_CPF_Medico` ASC) VISIBLE,
  INDEX `fk_Paciente_has_Medico_Paciente1_idx` (`Paciente_Codigo_Paciente` ASC, `Paciente_CPF_Paciente` ASC, `Paciente_Enfermaria_Codigo_Enfermaria` ASC, `Paciente_Enfermaria_Hospital_Codigo_Hospital` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_has_Medico_Paciente1`
    FOREIGN KEY (`Paciente_Codigo_Paciente` , `Paciente_CPF_Paciente` , `Paciente_Enfermaria_Codigo_Enfermaria` , `Paciente_Enfermaria_Hospital_Codigo_Hospital`)
    REFERENCES `SistemaHospitalar`.`Paciente` (`Codigo_Paciente` , `CPF_Paciente` , `Enfermaria_Codigo_Enfermaria` , `Enfermaria_Hospital_Codigo_Hospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_has_Medico_Medico1`
    FOREIGN KEY (`Medico_CRM` , `Medico_CPF_Medico`)
    REFERENCES `SistemaHospitalar`.`Medico` (`CRM` , `CPF_Medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Exame` (
  `Codigo_Exame` INT NOT NULL,
  `Descricao_Exame` VARCHAR(45) NOT NULL,
  `Restricao_Exame` VARCHAR(45) NOT NULL,
  `Valor_Exame` FLOAT NOT NULL,
  `Atende_Paciente_Codigo_Paciente` INT NOT NULL,
  `Atende_Paciente_CPF_Paciente` INT NOT NULL,
  `Atende_Paciente_Enfermaria_Codigo_Enfermaria` INT NOT NULL,
  `Atende_Paciente_Enfermaria_Hospital_Codigo_Hospital` INT NOT NULL,
  `Atende_Medico_CRM` INT NOT NULL,
  `Atende_Medico_CPF_Medico` INT NOT NULL,
  `Laboratorio_Codigo_Laboratorio` INT NOT NULL,
  `Laboratorio_Endereco_Codigo_Endereco` INT NOT NULL,
  `Laboratorio_Endereco_Bairro_Codigo_Bairro` INT NOT NULL,
  `Laboratorio_Endereco_Bairro_Cidade_Codigo_Cidade` INT NOT NULL,
  `Laboratorio_Endereco_Bairro_Cidade_UF_ID_UF` INT NOT NULL,
  `Laboratorio_Endereco_Bairro_Cidade_UF_Pais_ID_Pais` INT NOT NULL,
  `Laboratorio_Endereco_Tipo_Endereco_Codigo_TipoEnde` INT NOT NULL,
  PRIMARY KEY (`Codigo_Exame`, `Atende_Paciente_Codigo_Paciente`, `Atende_Paciente_CPF_Paciente`, `Atende_Paciente_Enfermaria_Codigo_Enfermaria`, `Atende_Paciente_Enfermaria_Hospital_Codigo_Hospital`, `Atende_Medico_CRM`, `Atende_Medico_CPF_Medico`, `Laboratorio_Codigo_Laboratorio`, `Laboratorio_Endereco_Codigo_Endereco`, `Laboratorio_Endereco_Bairro_Codigo_Bairro`, `Laboratorio_Endereco_Bairro_Cidade_Codigo_Cidade`, `Laboratorio_Endereco_Bairro_Cidade_UF_ID_UF`, `Laboratorio_Endereco_Bairro_Cidade_UF_Pais_ID_Pais`, `Laboratorio_Endereco_Tipo_Endereco_Codigo_TipoEnde`),
  INDEX `fk_Exame_Atende1_idx` (`Atende_Paciente_Codigo_Paciente` ASC, `Atende_Paciente_CPF_Paciente` ASC, `Atende_Paciente_Enfermaria_Codigo_Enfermaria` ASC, `Atende_Paciente_Enfermaria_Hospital_Codigo_Hospital` ASC, `Atende_Medico_CRM` ASC, `Atende_Medico_CPF_Medico` ASC) VISIBLE,
  INDEX `fk_Exame_Laboratorio1_idx` (`Laboratorio_Codigo_Laboratorio` ASC, `Laboratorio_Endereco_Codigo_Endereco` ASC, `Laboratorio_Endereco_Bairro_Codigo_Bairro` ASC, `Laboratorio_Endereco_Bairro_Cidade_Codigo_Cidade` ASC, `Laboratorio_Endereco_Bairro_Cidade_UF_ID_UF` ASC, `Laboratorio_Endereco_Bairro_Cidade_UF_Pais_ID_Pais` ASC, `Laboratorio_Endereco_Tipo_Endereco_Codigo_TipoEnde` ASC) VISIBLE,
  CONSTRAINT `fk_Exame_Atende1`
    FOREIGN KEY (`Atende_Paciente_Codigo_Paciente` , `Atende_Paciente_CPF_Paciente` , `Atende_Paciente_Enfermaria_Codigo_Enfermaria` , `Atende_Paciente_Enfermaria_Hospital_Codigo_Hospital` , `Atende_Medico_CRM` , `Atende_Medico_CPF_Medico`)
    REFERENCES `SistemaHospitalar`.`Atende` (`Paciente_Codigo_Paciente` , `Paciente_CPF_Paciente` , `Paciente_Enfermaria_Codigo_Enfermaria` , `Paciente_Enfermaria_Hospital_Codigo_Hospital` , `Medico_CRM` , `Medico_CPF_Medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exame_Laboratorio1`
    FOREIGN KEY (`Laboratorio_Codigo_Laboratorio` , `Laboratorio_Endereco_Codigo_Endereco` , `Laboratorio_Endereco_Bairro_Codigo_Bairro` , `Laboratorio_Endereco_Bairro_Cidade_Codigo_Cidade` , `Laboratorio_Endereco_Bairro_Cidade_UF_ID_UF` , `Laboratorio_Endereco_Bairro_Cidade_UF_Pais_ID_Pais` , `Laboratorio_Endereco_Tipo_Endereco_Codigo_TipoEnde`)
    REFERENCES `SistemaHospitalar`.`Laboratorio` (`Codigo_Laboratorio` , `Endereco_Codigo_Endereco` , `Endereco_Bairro_Codigo_Bairro` , `Endereco_Bairro_Cidade_Codigo_Cidade` , `Endereco_Bairro_Cidade_UF_ID_UF` , `Endereco_Bairro_Cidade_UF_Pais_ID_Pais` , `Endereco_Tipo_Endereco_Codigo_TipoEnde`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Convenio` (
  `Codigo_Convenio` INT NOT NULL,
  `Descricao_Convenio` VARCHAR(45) NOT NULL,
  `Valor_Convenio` FLOAT NULL DEFAULT NULL,
  `Tipo_Convenio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo_Convenio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Tipo_Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Tipo_Telefone` (
  `Codigo_TipoFone` INT NOT NULL,
  `Descricao_TipoFone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo_TipoFone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Telefone` (
  `Codigo_Telefone` INT NOT NULL,
  `DDD_Telefone` INT NOT NULL,
  `Numero_Telefone` INT NOT NULL,
  `Tipo_Telefone_Codigo_TipoFone` INT NOT NULL,
  `Medico_CRM` INT NOT NULL,
  `Medico_CPF_Medico` INT NOT NULL,
  `Enfermeiro_COREN` INT NOT NULL,
  `Enfermeiro_CPF_Enfermeiro` INT NOT NULL,
  `Enfermeiro_Enfermaria_Codigo_Enfermaria` INT NOT NULL,
  `Enfermeiro_Enfermaria_Hospital_Codigo_Hospital` INT NOT NULL,
  PRIMARY KEY (`Codigo_Telefone`, `Tipo_Telefone_Codigo_TipoFone`, `Medico_CRM`, `Medico_CPF_Medico`, `Enfermeiro_COREN`, `Enfermeiro_CPF_Enfermeiro`, `Enfermeiro_Enfermaria_Codigo_Enfermaria`, `Enfermeiro_Enfermaria_Hospital_Codigo_Hospital`),
  INDEX `fk_Telefone_Tipo_Telefone1_idx` (`Tipo_Telefone_Codigo_TipoFone` ASC) VISIBLE,
  INDEX `fk_Telefone_Medico1_idx` (`Medico_CRM` ASC, `Medico_CPF_Medico` ASC) VISIBLE,
  INDEX `fk_Telefone_Enfermeiro1_idx` (`Enfermeiro_COREN` ASC, `Enfermeiro_CPF_Enfermeiro` ASC, `Enfermeiro_Enfermaria_Codigo_Enfermaria` ASC, `Enfermeiro_Enfermaria_Hospital_Codigo_Hospital` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_Tipo_Telefone1`
    FOREIGN KEY (`Tipo_Telefone_Codigo_TipoFone`)
    REFERENCES `SistemaHospitalar`.`Tipo_Telefone` (`Codigo_TipoFone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefone_Medico1`
    FOREIGN KEY (`Medico_CRM` , `Medico_CPF_Medico`)
    REFERENCES `SistemaHospitalar`.`Medico` (`CRM` , `CPF_Medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefone_Enfermeiro1`
    FOREIGN KEY (`Enfermeiro_COREN` , `Enfermeiro_CPF_Enfermeiro` , `Enfermeiro_Enfermaria_Codigo_Enfermaria` , `Enfermeiro_Enfermaria_Hospital_Codigo_Hospital`)
    REFERENCES `SistemaHospitalar`.`Enfermeiro` (`COREN` , `CPF_Enfermeiro` , `Enfermaria_Codigo_Enfermaria` , `Enfermaria_Hospital_Codigo_Hospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Remedio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Remedio` (
  `Codigo_Remedio` INT NOT NULL,
  `Nome_Remedio` VARCHAR(45) NOT NULL,
  `Objetivo_Remedo` VARCHAR(45) NOT NULL,
  `Horarios_Remedio` DATETIME NOT NULL,
  `Atende_Paciente_Codigo_Paciente` INT NOT NULL,
  `Atende_Paciente_CPF_Paciente` INT NOT NULL,
  `Atende_Paciente_Enfermaria_Codigo_Enfermaria` INT NOT NULL,
  `Atende_Paciente_Enfermaria_Hospital_Codigo_Hospital` INT NOT NULL,
  `Atende_Medico_CRM` INT NOT NULL,
  `Atende_Medico_CPF_Medico` INT NOT NULL,
  PRIMARY KEY (`Codigo_Remedio`, `Atende_Paciente_Codigo_Paciente`, `Atende_Paciente_CPF_Paciente`, `Atende_Paciente_Enfermaria_Codigo_Enfermaria`, `Atende_Paciente_Enfermaria_Hospital_Codigo_Hospital`, `Atende_Medico_CRM`, `Atende_Medico_CPF_Medico`),
  INDEX `fk_Remedio_Atende1_idx` (`Atende_Paciente_Codigo_Paciente` ASC, `Atende_Paciente_CPF_Paciente` ASC, `Atende_Paciente_Enfermaria_Codigo_Enfermaria` ASC, `Atende_Paciente_Enfermaria_Hospital_Codigo_Hospital` ASC, `Atende_Medico_CRM` ASC, `Atende_Medico_CPF_Medico` ASC) VISIBLE,
  CONSTRAINT `fk_Remedio_Atende1`
    FOREIGN KEY (`Atende_Paciente_Codigo_Paciente` , `Atende_Paciente_CPF_Paciente` , `Atende_Paciente_Enfermaria_Codigo_Enfermaria` , `Atende_Paciente_Enfermaria_Hospital_Codigo_Hospital` , `Atende_Medico_CRM` , `Atende_Medico_CPF_Medico`)
    REFERENCES `SistemaHospitalar`.`Atende` (`Paciente_Codigo_Paciente` , `Paciente_CPF_Paciente` , `Paciente_Enfermaria_Codigo_Enfermaria` , `Paciente_Enfermaria_Hospital_Codigo_Hospital` , `Medico_CRM` , `Medico_CPF_Medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Trabalha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Trabalha` (
  `Hospital_Codigo_Hospital` INT NOT NULL,
  `Laboratorio_Codigo_Laboratorio` INT NOT NULL,
  PRIMARY KEY (`Hospital_Codigo_Hospital`, `Laboratorio_Codigo_Laboratorio`),
  INDEX `fk_Hospital_has_Laboratorio_Laboratorio1_idx` (`Laboratorio_Codigo_Laboratorio` ASC) VISIBLE,
  INDEX `fk_Hospital_has_Laboratorio_Hospital1_idx` (`Hospital_Codigo_Hospital` ASC) VISIBLE,
  CONSTRAINT `fk_Hospital_has_Laboratorio_Hospital1`
    FOREIGN KEY (`Hospital_Codigo_Hospital`)
    REFERENCES `SistemaHospitalar`.`Hospital` (`ID_Hospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospital_has_Laboratorio_Laboratorio1`
    FOREIGN KEY (`Laboratorio_Codigo_Laboratorio`)
    REFERENCES `SistemaHospitalar`.`Laboratorio` (`Codigo_Laboratorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Tem_Parceria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Tem_Parceria` (
  `Hospital_Codigo_Hospital` INT NOT NULL,
  `Convenio_Codigo_Convenio` INT NOT NULL,
  PRIMARY KEY (`Hospital_Codigo_Hospital`, `Convenio_Codigo_Convenio`),
  INDEX `fk_Hospital_has_Convenio_Convenio1_idx` (`Convenio_Codigo_Convenio` ASC) VISIBLE,
  INDEX `fk_Hospital_has_Convenio_Hospital1_idx` (`Hospital_Codigo_Hospital` ASC) VISIBLE,
  CONSTRAINT `fk_Hospital_has_Convenio_Hospital1`
    FOREIGN KEY (`Hospital_Codigo_Hospital`)
    REFERENCES `SistemaHospitalar`.`Hospital` (`ID_Hospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospital_has_Convenio_Convenio1`
    FOREIGN KEY (`Convenio_Codigo_Convenio`)
    REFERENCES `SistemaHospitalar`.`Convenio` (`Codigo_Convenio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Paciente_Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Paciente_Telefone` (
  `Paciente_Codigo_Paciente` INT NOT NULL,
  `Paciente_CPF_Paciente` INT NOT NULL,
  `Paciente_Enfermaria_Codigo_Enfermaria` INT NOT NULL,
  `Paciente_Enfermaria_Hospital_Codigo_Hospital` INT NOT NULL,
  `Telefone_Codigo_Telefone` INT NOT NULL,
  `Telefone_Tipo_Telefone_Codigo_TipoFone` INT NOT NULL,
  PRIMARY KEY (`Paciente_Codigo_Paciente`, `Paciente_CPF_Paciente`, `Paciente_Enfermaria_Codigo_Enfermaria`, `Paciente_Enfermaria_Hospital_Codigo_Hospital`, `Telefone_Codigo_Telefone`, `Telefone_Tipo_Telefone_Codigo_TipoFone`),
  INDEX `fk_Paciente_has_Telefone_Telefone1_idx` (`Telefone_Codigo_Telefone` ASC, `Telefone_Tipo_Telefone_Codigo_TipoFone` ASC) VISIBLE,
  INDEX `fk_Paciente_has_Telefone_Paciente1_idx` (`Paciente_Codigo_Paciente` ASC, `Paciente_CPF_Paciente` ASC, `Paciente_Enfermaria_Codigo_Enfermaria` ASC, `Paciente_Enfermaria_Hospital_Codigo_Hospital` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_has_Telefone_Paciente1`
    FOREIGN KEY (`Paciente_Codigo_Paciente` , `Paciente_CPF_Paciente` , `Paciente_Enfermaria_Codigo_Enfermaria` , `Paciente_Enfermaria_Hospital_Codigo_Hospital`)
    REFERENCES `SistemaHospitalar`.`Paciente` (`Codigo_Paciente` , `CPF_Paciente` , `Enfermaria_Codigo_Enfermaria` , `Enfermaria_Hospital_Codigo_Hospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_has_Telefone_Telefone1`
    FOREIGN KEY (`Telefone_Codigo_Telefone` , `Telefone_Tipo_Telefone_Codigo_TipoFone`)
    REFERENCES `SistemaHospitalar`.`Telefone` (`Codigo_Telefone` , `Tipo_Telefone_Codigo_TipoFone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Possui`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Possui` (
  `Hospital_ID_Hospital` INT NOT NULL,
  `Medico_CRM` INT NOT NULL,
  `Medico_CPF_Medico` INT NOT NULL,
  `Medico_Sexo_Codigo_Sexo` INT NOT NULL,
  PRIMARY KEY (`Hospital_ID_Hospital`, `Medico_CRM`, `Medico_CPF_Medico`, `Medico_Sexo_Codigo_Sexo`),
  INDEX `fk_Hospital_has_Medico_Medico1_idx` (`Medico_CRM` ASC, `Medico_CPF_Medico` ASC, `Medico_Sexo_Codigo_Sexo` ASC) VISIBLE,
  INDEX `fk_Hospital_has_Medico_Hospital1_idx` (`Hospital_ID_Hospital` ASC) VISIBLE,
  CONSTRAINT `fk_Hospital_has_Medico_Hospital1`
    FOREIGN KEY (`Hospital_ID_Hospital`)
    REFERENCES `SistemaHospitalar`.`Hospital` (`ID_Hospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospital_has_Medico_Medico1`
    FOREIGN KEY (`Medico_CRM` , `Medico_CPF_Medico` , `Medico_Sexo_Codigo_Sexo`)
    REFERENCES `SistemaHospitalar`.`Medico` (`CRM` , `CPF_Medico` , `Sexo_Codigo_Sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Medico_Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Medico_Endereco` (
  `Medico_CRM` INT NOT NULL,
  `Medico_CPF_Medico` INT NOT NULL,
  `Medico_Sexo_Codigo_Sexo` INT NOT NULL,
  `Endereco_Codigo_Endereco` INT NOT NULL,
  `Endereco_Bairro_Codigo_Bairro` INT NOT NULL,
  `Endereco_Bairro_Cidade_Codigo_Cidade` INT NOT NULL,
  `Endereco_Bairro_Cidade_UF_ID_UF` INT NOT NULL,
  `Endereco_Bairro_Cidade_UF_Pais_ID_Pais` INT NOT NULL,
  `Endereco_Tipo_Endereco_Codigo_TipoEnde` INT NOT NULL,
  PRIMARY KEY (`Medico_CRM`, `Medico_CPF_Medico`, `Medico_Sexo_Codigo_Sexo`, `Endereco_Codigo_Endereco`, `Endereco_Bairro_Codigo_Bairro`, `Endereco_Bairro_Cidade_Codigo_Cidade`, `Endereco_Bairro_Cidade_UF_ID_UF`, `Endereco_Bairro_Cidade_UF_Pais_ID_Pais`, `Endereco_Tipo_Endereco_Codigo_TipoEnde`),
  INDEX `fk_Medico_has_Endereco_Endereco1_idx` (`Endereco_Codigo_Endereco` ASC, `Endereco_Bairro_Codigo_Bairro` ASC, `Endereco_Bairro_Cidade_Codigo_Cidade` ASC, `Endereco_Bairro_Cidade_UF_ID_UF` ASC, `Endereco_Bairro_Cidade_UF_Pais_ID_Pais` ASC, `Endereco_Tipo_Endereco_Codigo_TipoEnde` ASC) VISIBLE,
  INDEX `fk_Medico_has_Endereco_Medico1_idx` (`Medico_CRM` ASC, `Medico_CPF_Medico` ASC, `Medico_Sexo_Codigo_Sexo` ASC) VISIBLE,
  CONSTRAINT `fk_Medico_has_Endereco_Medico1`
    FOREIGN KEY (`Medico_CRM` , `Medico_CPF_Medico` , `Medico_Sexo_Codigo_Sexo`)
    REFERENCES `SistemaHospitalar`.`Medico` (`CRM` , `CPF_Medico` , `Sexo_Codigo_Sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medico_has_Endereco_Endereco1`
    FOREIGN KEY (`Endereco_Codigo_Endereco` , `Endereco_Bairro_Codigo_Bairro` , `Endereco_Bairro_Cidade_Codigo_Cidade` , `Endereco_Bairro_Cidade_UF_ID_UF` , `Endereco_Bairro_Cidade_UF_Pais_ID_Pais` , `Endereco_Tipo_Endereco_Codigo_TipoEnde`)
    REFERENCES `SistemaHospitalar`.`Endereco` (`Codigo_Endereco` , `Bairro_Codigo_Bairro` , `Bairro_Cidade_Codigo_Cidade` , `Bairro_Cidade_UF_ID_UF` , `Bairro_Cidade_UF_Pais_ID_Pais` , `Tipo_Endereco_Codigo_TipoEnde`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Paciente_Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Paciente_Endereco` (
  `Paciente_Codigo_Paciente` INT NOT NULL,
  `Paciente_CPF_Paciente` INT NOT NULL,
  `Paciente_Enfermaria_Codigo_Enfermaria` INT NOT NULL,
  `Paciente_Enfermaria_Hospital_Codigo_Hospital` INT NOT NULL,
  `Paciente_Sexo_Codigo_Sexo` INT NOT NULL,
  `Endereco_Codigo_Endereco` INT NOT NULL,
  `Endereco_Bairro_Codigo_Bairro` INT NOT NULL,
  `Endereco_Bairro_Cidade_Codigo_Cidade` INT NOT NULL,
  `Endereco_Bairro_Cidade_UF_ID_UF` INT NOT NULL,
  `Endereco_Bairro_Cidade_UF_Pais_ID_Pais` INT NOT NULL,
  `Endereco_Tipo_Endereco_Codigo_TipoEnde` INT NOT NULL,
  PRIMARY KEY (`Paciente_Codigo_Paciente`, `Paciente_CPF_Paciente`, `Paciente_Enfermaria_Codigo_Enfermaria`, `Paciente_Enfermaria_Hospital_Codigo_Hospital`, `Paciente_Sexo_Codigo_Sexo`, `Endereco_Codigo_Endereco`, `Endereco_Bairro_Codigo_Bairro`, `Endereco_Bairro_Cidade_Codigo_Cidade`, `Endereco_Bairro_Cidade_UF_ID_UF`, `Endereco_Bairro_Cidade_UF_Pais_ID_Pais`, `Endereco_Tipo_Endereco_Codigo_TipoEnde`),
  INDEX `fk_Paciente_has_Endereco_Endereco1_idx` (`Endereco_Codigo_Endereco` ASC, `Endereco_Bairro_Codigo_Bairro` ASC, `Endereco_Bairro_Cidade_Codigo_Cidade` ASC, `Endereco_Bairro_Cidade_UF_ID_UF` ASC, `Endereco_Bairro_Cidade_UF_Pais_ID_Pais` ASC, `Endereco_Tipo_Endereco_Codigo_TipoEnde` ASC) VISIBLE,
  INDEX `fk_Paciente_has_Endereco_Paciente1_idx` (`Paciente_Codigo_Paciente` ASC, `Paciente_CPF_Paciente` ASC, `Paciente_Enfermaria_Codigo_Enfermaria` ASC, `Paciente_Enfermaria_Hospital_Codigo_Hospital` ASC, `Paciente_Sexo_Codigo_Sexo` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_has_Endereco_Paciente1`
    FOREIGN KEY (`Paciente_Codigo_Paciente` , `Paciente_CPF_Paciente` , `Paciente_Enfermaria_Codigo_Enfermaria` , `Paciente_Enfermaria_Hospital_Codigo_Hospital` , `Paciente_Sexo_Codigo_Sexo`)
    REFERENCES `SistemaHospitalar`.`Paciente` (`Codigo_Paciente` , `CPF_Paciente` , `Enfermaria_Codigo_Enfermaria` , `Enfermaria_Hospital_Codigo_Hospital` , `Sexo_Codigo_Sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_has_Endereco_Endereco1`
    FOREIGN KEY (`Endereco_Codigo_Endereco` , `Endereco_Bairro_Codigo_Bairro` , `Endereco_Bairro_Cidade_Codigo_Cidade` , `Endereco_Bairro_Cidade_UF_ID_UF` , `Endereco_Bairro_Cidade_UF_Pais_ID_Pais` , `Endereco_Tipo_Endereco_Codigo_TipoEnde`)
    REFERENCES `SistemaHospitalar`.`Endereco` (`Codigo_Endereco` , `Bairro_Codigo_Bairro` , `Bairro_Cidade_Codigo_Cidade` , `Bairro_Cidade_UF_ID_UF` , `Bairro_Cidade_UF_Pais_ID_Pais` , `Tipo_Endereco_Codigo_TipoEnde`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaHospitalar`.`Enfermeiro_Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaHospitalar`.`Enfermeiro_Endereco` (
  `Enfermeiro_COREN` INT NOT NULL,
  `Enfermeiro_CPF_Enfermeiro` INT NOT NULL,
  `Enfermeiro_Enfermaria_Codigo_Enfermaria` INT NOT NULL,
  `Enfermeiro_Enfermaria_Hospital_Codigo_Hospital` INT NOT NULL,
  `Enfermeiro_Sexo_Codigo_Sexo` INT NOT NULL,
  `Endereco_Codigo_Endereco` INT NOT NULL,
  `Endereco_Bairro_Codigo_Bairro` INT NOT NULL,
  `Endereco_Bairro_Cidade_Codigo_Cidade` INT NOT NULL,
  `Endereco_Bairro_Cidade_UF_ID_UF` INT NOT NULL,
  `Endereco_Bairro_Cidade_UF_Pais_ID_Pais` INT NOT NULL,
  `Endereco_Tipo_Endereco_Codigo_TipoEnde` INT NOT NULL,
  PRIMARY KEY (`Enfermeiro_COREN`, `Enfermeiro_CPF_Enfermeiro`, `Enfermeiro_Enfermaria_Codigo_Enfermaria`, `Enfermeiro_Enfermaria_Hospital_Codigo_Hospital`, `Enfermeiro_Sexo_Codigo_Sexo`, `Endereco_Codigo_Endereco`, `Endereco_Bairro_Codigo_Bairro`, `Endereco_Bairro_Cidade_Codigo_Cidade`, `Endereco_Bairro_Cidade_UF_ID_UF`, `Endereco_Bairro_Cidade_UF_Pais_ID_Pais`, `Endereco_Tipo_Endereco_Codigo_TipoEnde`),
  INDEX `fk_Enfermeiro_has_Endereco_Endereco1_idx` (`Endereco_Codigo_Endereco` ASC, `Endereco_Bairro_Codigo_Bairro` ASC, `Endereco_Bairro_Cidade_Codigo_Cidade` ASC, `Endereco_Bairro_Cidade_UF_ID_UF` ASC, `Endereco_Bairro_Cidade_UF_Pais_ID_Pais` ASC, `Endereco_Tipo_Endereco_Codigo_TipoEnde` ASC) VISIBLE,
  INDEX `fk_Enfermeiro_has_Endereco_Enfermeiro1_idx` (`Enfermeiro_COREN` ASC, `Enfermeiro_CPF_Enfermeiro` ASC, `Enfermeiro_Enfermaria_Codigo_Enfermaria` ASC, `Enfermeiro_Enfermaria_Hospital_Codigo_Hospital` ASC, `Enfermeiro_Sexo_Codigo_Sexo` ASC) VISIBLE,
  CONSTRAINT `fk_Enfermeiro_has_Endereco_Enfermeiro1`
    FOREIGN KEY (`Enfermeiro_COREN` , `Enfermeiro_CPF_Enfermeiro` , `Enfermeiro_Enfermaria_Codigo_Enfermaria` , `Enfermeiro_Enfermaria_Hospital_Codigo_Hospital` , `Enfermeiro_Sexo_Codigo_Sexo`)
    REFERENCES `SistemaHospitalar`.`Enfermeiro` (`COREN` , `CPF_Enfermeiro` , `Enfermaria_Codigo_Enfermaria` , `Enfermaria_Hospital_Codigo_Hospital` , `Sexo_Codigo_Sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enfermeiro_has_Endereco_Endereco1`
    FOREIGN KEY (`Endereco_Codigo_Endereco` , `Endereco_Bairro_Codigo_Bairro` , `Endereco_Bairro_Cidade_Codigo_Cidade` , `Endereco_Bairro_Cidade_UF_ID_UF` , `Endereco_Bairro_Cidade_UF_Pais_ID_Pais` , `Endereco_Tipo_Endereco_Codigo_TipoEnde`)
    REFERENCES `SistemaHospitalar`.`Endereco` (`Codigo_Endereco` , `Bairro_Codigo_Bairro` , `Bairro_Cidade_Codigo_Cidade` , `Bairro_Cidade_UF_ID_UF` , `Bairro_Cidade_UF_Pais_ID_Pais` , `Tipo_Endereco_Codigo_TipoEnde`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
